// Search page
const SEARCH_CURRENT_PAGE_UPDATE = 'SEARCH_CURRENT_PAGE_UPDATE';
const SEARCH_NEXT_PAGE_UPDATE = 'SEARCH_NEXT_PAGE_UPDATE';

export {
  SEARCH_CURRENT_PAGE_UPDATE,
  SEARCH_NEXT_PAGE_UPDATE,
};
